package top.ekiz.whitenoise.domain

enum class NoiseType {
    WHITE, PINK, BROWN, DEEP_BROWN, BLUE, VIOLET, GREY, GREEN, BLACK,
    VELVET, OCEAN_WAVES, BINAURAL_BEATS, WIND, AIRPLANE_CABIN, HEARTBEAT
}
